### ISSUE TITLE
Rendered obsolete by Tokio-Fs

### ISSUE THREAD

**Issue by Thomspoon** [seanmonstar/futures-fs#14]
Hello,

I was wondering if futures-fs was rendered obsolete by the release of tokio-fs by any chance? There seems to be quite a bit of overlap, and with the #[blocking] api, it seems as though most of the functions covered here are now covered by tokio.

**Comment by seanmonstar** [comment]
You can definitely use the blocking API in tokio instead, and it may even have better perfomance in some cases, but using it requires using the tokio threadpool. This crate still allows accessing the file system off thread with a futures API, so I think it's still relevant.

**Comment by Thomspoon** [comment]
Thanks for the response! I'm not sure I fully understand the difference of the futures API and the blocking API then, I figured bother were doing roughly the same thing only futures are event-based rather than thread-based. Tokio has OpenFuture<> and CloseFuture<> but I guess that's where the futures end and the moving the event loop begins.

**Comment by seanmonstar** [comment]
The implementation is a bit different, the end result is similar: have FS operations with a `Future` API when you don't want to block a certain thread.

**futures-fs** keeps a separate thread pool, and uses message passing to send buffers from the user thread to the thread pool and back in a `Future`. It can work in just about any instance.

**tokio-fs** uses implementation details of the `tokio-threadpool`, instead of sending owned buffers over channels, it moves the current thread to a state allowing for it to block, up to a maximum number of threads blocked at a time. This keeps some threads still working on non-blocking tasks.

**Comment by Thomspoon** [comment]
Thanks for the explanation. I think I will keep using futures-fs because it sounds lightweight compared to tokio, and I'm already familiar with the API :).
